# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cards.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cards.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x63\x61rds.proto\"0\n\x04\x43\x61rd\x12\x13\n\x04\x46\x61\x63\x65\x18\x01 \x01(\x0e\x32\x05.Face\x12\x13\n\x04Suit\x18\x02 \x01(\x0e\x32\x05.Suit\"\x1d\n\x05\x43\x61rds\x12\x14\n\x05\x43\x61rds\x18\x01 \x03(\x0b\x32\x05.Card*\x99\x01\n\x04\x46\x61\x63\x65\x12\x0f\n\x0b\x46\x61\x63\x65\x44\x65\x66\x61ult\x10\x00\x12\x07\n\x03Two\x10\x02\x12\t\n\x05Three\x10\x03\x12\x08\n\x04\x46our\x10\x04\x12\x08\n\x04\x46ive\x10\x05\x12\x07\n\x03Six\x10\x06\x12\t\n\x05Seven\x10\x07\x12\x08\n\x04Nine\x10\t\x12\t\n\x05\x45ight\x10\x08\x12\x07\n\x03Ten\x10\n\x12\x08\n\x04Jack\x10\x0b\x12\t\n\x05Queen\x10\x0c\x12\x08\n\x04King\x10\r\x12\x07\n\x03\x41\x63\x65\x10\x0e*H\n\x04Suit\x12\x0f\n\x0bSuitDefault\x10\x00\x12\x0c\n\x08\x44iamonds\x10\x01\x12\t\n\x05\x43lubs\x10\x02\x12\n\n\x06Hearts\x10\x03\x12\n\n\x06Spades\x10\x04*\xb2\x01\n\tCardsType\x12\x14\n\x10\x43\x61rdsTypeDefault\x10\x00\x12\x0c\n\x08HighCard\x10\x02\x12\x08\n\x04Pair\x10\x03\x12\x0b\n\x07TwoPair\x10\x04\x12\x0f\n\x0bThreeOfKind\x10\x05\x12\x0c\n\x08Straight\x10\x06\x12\t\n\x05\x46lush\x10\x07\x12\r\n\tFullHouse\x10\x08\x12\x0e\n\nFourOfKind\x10\t\x12\x11\n\rStraightFlush\x10\n\x12\x0e\n\nRoyalFlush\x10\x0b\x42\x32\n\x10\x63om.baiyigame.pbZ\x02pb\xaa\x02\x19\x43om.Baiyigame.Godnet.Commb\x06proto3')
)

_FACE = _descriptor.EnumDescriptor(
  name='Face',
  full_name='Face',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FaceDefault', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Two', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Three', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Four', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Five', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Six', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Seven', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Nine', index=7, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Eight', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ten', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jack', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Queen', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='King', index=12, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ace', index=13, number=14,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=97,
  serialized_end=250,
)
_sym_db.RegisterEnumDescriptor(_FACE)

Face = enum_type_wrapper.EnumTypeWrapper(_FACE)
_SUIT = _descriptor.EnumDescriptor(
  name='Suit',
  full_name='Suit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SuitDefault', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Diamonds', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Clubs', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hearts', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Spades', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=252,
  serialized_end=324,
)
_sym_db.RegisterEnumDescriptor(_SUIT)

Suit = enum_type_wrapper.EnumTypeWrapper(_SUIT)
_CARDSTYPE = _descriptor.EnumDescriptor(
  name='CardsType',
  full_name='CardsType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CardsTypeDefault', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HighCard', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Pair', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TwoPair', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ThreeOfKind', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Straight', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Flush', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FullHouse', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FourOfKind', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StraightFlush', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RoyalFlush', index=10, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=327,
  serialized_end=505,
)
_sym_db.RegisterEnumDescriptor(_CARDSTYPE)

CardsType = enum_type_wrapper.EnumTypeWrapper(_CARDSTYPE)
FaceDefault = 0
Two = 2
Three = 3
Four = 4
Five = 5
Six = 6
Seven = 7
Nine = 9
Eight = 8
Ten = 10
Jack = 11
Queen = 12
King = 13
Ace = 14
SuitDefault = 0
Diamonds = 1
Clubs = 2
Hearts = 3
Spades = 4
CardsTypeDefault = 0
HighCard = 2
Pair = 3
TwoPair = 4
ThreeOfKind = 5
Straight = 6
Flush = 7
FullHouse = 8
FourOfKind = 9
StraightFlush = 10
RoyalFlush = 11



_CARD = _descriptor.Descriptor(
  name='Card',
  full_name='Card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Face', full_name='Card.Face', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Suit', full_name='Card.Suit', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=63,
)


_CARDS = _descriptor.Descriptor(
  name='Cards',
  full_name='Cards',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cards', full_name='Cards.Cards', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=94,
)

_CARD.fields_by_name['Face'].enum_type = _FACE
_CARD.fields_by_name['Suit'].enum_type = _SUIT
_CARDS.fields_by_name['Cards'].message_type = _CARD
DESCRIPTOR.message_types_by_name['Card'] = _CARD
DESCRIPTOR.message_types_by_name['Cards'] = _CARDS
DESCRIPTOR.enum_types_by_name['Face'] = _FACE
DESCRIPTOR.enum_types_by_name['Suit'] = _SUIT
DESCRIPTOR.enum_types_by_name['CardsType'] = _CARDSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Card = _reflection.GeneratedProtocolMessageType('Card', (_message.Message,), dict(
  DESCRIPTOR = _CARD,
  __module__ = 'cards_pb2'
  # @@protoc_insertion_point(class_scope:Card)
  ))
_sym_db.RegisterMessage(Card)

Cards = _reflection.GeneratedProtocolMessageType('Cards', (_message.Message,), dict(
  DESCRIPTOR = _CARDS,
  __module__ = 'cards_pb2'
  # @@protoc_insertion_point(class_scope:Cards)
  ))
_sym_db.RegisterMessage(Cards)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020com.baiyigame.pbZ\002pb\252\002\031Com.Baiyigame.Godnet.Comm'))
# @@protoc_insertion_point(module_scope)
