# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='rpcpb',
  syntax='proto3',
  serialized_pb=_b('\n\trpc.proto\x12\x05rpcpb\"\x82\x01\n\x07RPCInfo\x12\x0b\n\x03\x43id\x18\x01 \x01(\t\x12\n\n\x02\x46n\x18\x02 \x01(\t\x12\x0f\n\x07ReplyTo\x18\x03 \x01(\t\x12\r\n\x05track\x18\x04 \x01(\t\x12\x0f\n\x07\x45xpired\x18\x05 \x01(\x03\x12\r\n\x05Reply\x18\x06 \x01(\x08\x12\x10\n\x08\x41rgsType\x18\x07 \x03(\t\x12\x0c\n\x04\x41rgs\x18\x08 \x03(\x0c\"L\n\nResultInfo\x12\x0b\n\x03\x43id\x18\x01 \x01(\t\x12\r\n\x05\x45rror\x18\x02 \x01(\t\x12\x12\n\nResultType\x18\x04 \x01(\t\x12\x0e\n\x06Result\x18\x05 \x01(\x0c\x62\x06proto3')
)




_RPCINFO = _descriptor.Descriptor(
  name='RPCInfo',
  full_name='rpcpb.RPCInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cid', full_name='rpcpb.RPCInfo.Cid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Fn', full_name='rpcpb.RPCInfo.Fn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ReplyTo', full_name='rpcpb.RPCInfo.ReplyTo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track', full_name='rpcpb.RPCInfo.track', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Expired', full_name='rpcpb.RPCInfo.Expired', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Reply', full_name='rpcpb.RPCInfo.Reply', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ArgsType', full_name='rpcpb.RPCInfo.ArgsType', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Args', full_name='rpcpb.RPCInfo.Args', index=7,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=151,
)


_RESULTINFO = _descriptor.Descriptor(
  name='ResultInfo',
  full_name='rpcpb.ResultInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cid', full_name='rpcpb.ResultInfo.Cid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Error', full_name='rpcpb.ResultInfo.Error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ResultType', full_name='rpcpb.ResultInfo.ResultType', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Result', full_name='rpcpb.ResultInfo.Result', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['RPCInfo'] = _RPCINFO
DESCRIPTOR.message_types_by_name['ResultInfo'] = _RESULTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPCInfo = _reflection.GeneratedProtocolMessageType('RPCInfo', (_message.Message,), dict(
  DESCRIPTOR = _RPCINFO,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.RPCInfo)
  ))
_sym_db.RegisterMessage(RPCInfo)

ResultInfo = _reflection.GeneratedProtocolMessageType('ResultInfo', (_message.Message,), dict(
  DESCRIPTOR = _RESULTINFO,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.ResultInfo)
  ))
_sym_db.RegisterMessage(ResultInfo)


# @@protoc_insertion_point(module_scope)
